apache/pulsar-dotpulsar

.gitignore, docker-compose.yml, src/DotPulsar.Stress.Tests/ConsumerTests.cs, src/DotPulsar.Stress.Tests/DotPulsar.Stress.Tests.csproj, src/DotPulsar.Stress.Tests/EnumerableTaskExtensions.cs, src/DotPulsar.Stress.Tests/XunitExceptionHandler.cs, src/DotPulsar.sln, src/DotPulsar/Internal/Abstractions/IEvent.cs, src/DotPulsar/Internal/Abstractions/IProcess.cs, src/DotPulsar/Internal/ConsumerChannel.cs, src/DotPulsar/Internal/Extensions/MessagePackageExtensions.cs, src/DotPulsar/Internal/MessagePackageExtensions.cs, src/DotPulsar/Internal/PulsarStream.cs
Refactored ConsumerChannel message package validation to separate ack concerns. 
Fixes #16
=> Fixed pulsar stream bug with ReadOnlySequence.

src/DotPulsar/Abstractions/IPulsarClientBuilder.cs, src/DotPulsar/Internal/ConnectionPool.cs, src/DotPulsar/Internal/Constants.cs, src/DotPulsar/Internal/ConsumerBuilder.cs, src/DotPulsar/Internal/Extensions/MessagePackageExtensions.cs, src/DotPulsar/Internal/PulsarClientBuilder.cs, src/DotPulsar/Message.cs
Reverts danske-commodities/dotpulsar#19
=> Revert "Move payload command component sizes into constants + make inactive connections closing interval configurable"

.asf.yaml
*Motivation*
`.asf.yaml` is a configuration file that can be used for managing and
update ASF github repository settings
=> Use .asf.yaml for managing and update project settings

src/DotPulsar/Internal/PulsarClientBuilder.cs
Fixed token encoding differences.
=> Changed auth token encoding to match Java client (UTF8)

.github/workflows/ci-unit.yaml, README.md
Remove stress tests from CI.
Add ci badge in ReadMe.
closes #43
=> Remove stress test from CI

src/DotPulsar/Internal/AsyncQueue.cs
#53 fixed memory leak in AsyncQueue
=> Fix memory leak in AsyncQueue.cs

src/DotPulsar/Internal/ConsumerChannel.cs
=> Fix loading single message batches in consume

src/DotPulsar/Internal/ProducerChannelFactory.cs
Fixed issue with producing with schema to non existing topic
=> Fixed issue with producing with schema to non existing topic

src/DotPulsar/Abstractions/IProducerBuilder.cs, tests/DotPulsar.IntegrationTests/ProducerTests.cs
It was not properly tested for functionality in the single partition router test.
This PR fixes incorrect logic in the single partition router integration test.
=> Fix single partition router test

src/DotPulsar/Internal/Extensions/ReadOnlySequenceExtensions.cs, tests/DotPulsar.Tests/Internal/Extensions/ReadOnlySequenceExtensionsTests.cs
The loop would not correctly break after reading 4 bytes.
=> Fix performance issue with ReadUint32

src/DotPulsar/Internal/PulsarStream.cs
Use ReadAtLeast to wait until a usable amount of data is ready.
=> Performance tuning PulsarStream

.github/PULL_REQUEST_TEMPLATE/servicing_pull_request_template.md
Added
servicing_pull_request_template.md template for pull requests
=> Pull request template

CHANGELOG.md, src/DotPulsar/Internal/Connection.cs, src/DotPulsar/Internal/ConnectionPool.cs, src/DotPulsar/Internal/Producer.cs, tests/DotPulsar.Tests/IntegrationFixture.cs
Add changelog description of SendChannel addition
Update changelog, and minor code cleanup
=> Updated changelog for SendChannel

src/DotPulsar/Extensions/SendChannelExtensions.cs, tests/DotPulsar.Tests/ProducerTests.cs
Fixes Object Pooling issue in SendChannelExtensions
When using the send extension for SendChannel, metadata objects retrieved from the object pool were returned before broker confirmation was received, resulting in unintended reuse of those objects.
Introduced in non released code.
Expanded current integration tests to send multiple messages instead of only a single message.
=> Fix object pooling issue

src/DotPulsar/Internal/AsyncQueueWithCursor.cs
Fixes Memory leak in producer
AsyncQueueWithCursor.NextItem missing CancellationTokenRegistration disposal causing token to keep reference of all queue items
Introduced in 2.8.0 with internal rewrite of producer functionality
Manual testing with explicit garbage collection calls
=> Fix memory leak in Producer

README.md
Link to organization of initial work fixed.
Fixes #150 
Fixes the link to Danske Commodities organization
=> Fixed broken link in readme.md

src/DotPulsar/Internal/Abstractions/Process.cs, src/DotPulsar/Internal/ConsumerProcess.cs, src/DotPulsar/Internal/ProducerProcess.cs, src/DotPulsar/Internal/ReaderProcess.cs
Refactor
Convert all Process object to process actions asynchronously in order
Additionally explicitly close connection when establishing new channel in an attempt to fix issue with multiple channels for a consumer
=> Async Process

CHANGELOG.md
Updates changelog to reflect release 2.11.1
=> Update changelog after 2.11.1 release

README.md
Updated README.md to reflect DotPulsar support partitioned topics for the consumer.
=> Although README.md doesn't mention it, DotPulsar actually supports partitioned topics for the consumer.

.github/workflows/publish-to-nuget.yml
Small fix for publish-to-nuget.yml
=> Small fix for publish-to-nuget.yml

.github/workflows/publish-to-nuget.yml
Updated publish-to-nuget.yml to use dotnet 8
=> Updated publish-to-nuget.yml to use dotnet 8

src/DotPulsar/DotPulsar.csproj
Removed AssemblyVersion and FileVersion from csproj
=> Removed AssemblyVersion and FileVersion from csproj

.github/workflows/publish-to-nuget.yml
publish-to-nuget.yml -> Fix path
=> publish-to-nuget.yml ->Fix path

docs/release-process.md
=> docs: update release-process

docs/release-process.md
The changes in the release-process.md file have been made to make the instructions more clear and understandable. The steps in the process have been given more informative and unique titles.
Additionally, the naming convention for releases and pre-releases was corrected and unified across the document for consistency.
=> Release process documentation made more clear

docs/release-process.md
This is what we should fix in the next release 🤣
=> docs: emphasize the filename in release-process

docs/release-process.md
Made the "Describe this release" text box in GitHub more clear.
What do you think ?
=> Made the Describe this release text box in github more clear.

docs/release-process.md
=> docs: use variables in release-process

tests/DotPulsar.Tests/DotPulsar.Tests.csproj, tests/DotPulsar.Tests/IntegrationFixture.cs, tests/DotPulsar.Tests/Internal/ConsumerTests.cs, tests/DotPulsar.Tests/Internal/ProducerTests.cs, tests/DotPulsar.Tests/Internal/ReaderTests.cs, tests/DotPulsar.Tests/PulsarClientTests.cs
Migrated from [FluentDocker](https://github.com/mariotoffia/FluentDocker) to [Testcontainers](https://dotnet.testcontainers.org/)
=> Migrated from fluent docker to testcontainers

tests/DotPulsar.Tests/Internal/ConsumerTests.cs, tests/DotPulsar.Tests/Internal/ReaderTests.cs
Added connectivity tests for Consumer and Reader
=> Added connectivity tests for Consumer and Reader

docs/release_validation_macos.md
Shows how macOS users can validate DotPulsar releases
I think @lhotari has a mac and used this guide :)
=> Validating DotPulsar release on MacOS

docs/release_validation_linux_macos.md
Added Linux to release_validation_linux_macos.md
=> Added linux to release_validation_linux_macos.md

.asf.yaml, .github/workflows/publish-to-nuget.yml, NOTICE, docs/api/docfx.json
Sets the correct build path in docfx.
=> Docfx correct build path.

src/DotPulsar/Internal/Consumer.cs, src/DotPulsar/Internal/Reader.cs
Fixes #211 #208 
The changes in this pull request address concurrent read scenarios by introducing an `AsyncLock` to both the `Reader` and `Consumer` classes. The receive loop within these classes is now synchronized using this lock, ensuring proper management of concurrent reads. Additionally, the lock object is disposed during the disposal of the respective classes.
I manually verified that the `Receive` methods in the `Reader` and `Consumer` classes are now thread-safe, as expected.
=> Add AsyncLock to Reader and Consumer classes

DotPulsar.sln, samples/SendChannel/Program.cs, samples/SendChannel/SendChannel.csproj
Add sample for using send channel when producing messages
Add sample for using send channel when producing messages
=> Add sample using send channel

tests/DotPulsar.Tests/DotPulsar.Tests.csproj, tests/DotPulsar.Tests/IntegrationFixture.cs
Upgrade Testcontainers version and streamline Pulsar configuration
This commit enhances the Testcontainers version used in tests and incorporates the 'Testcontainers.Pulsar' package for improved integration. It significantly streamlines the establishment process for Pulsar during integration tests. The environment configuration and token creation procedures are now managed using specific methods from the 'Testcontainers.Pulsar' package. Additionally, the Testcontainers image version has also been updated.
All tests have been performed and are green.
=> Upgrade Testcontainers version and streamline Pulsar configuration

src/DotPulsar/Schema.cs, src/DotPulsar/Schemas/AvroGenericRecordSchema.cs, src/DotPulsar/Schemas/AvroISpecificRecordSchema.cs, tests/DotPulsar.Tests/Internal/ConsumerTests.cs, tests/DotPulsar.Tests/Internal/ProducerTests.cs, tests/DotPulsar.Tests/Schemas/AvroGenericRecordSchemaTests.cs
Fixes #255 
Implements read and write for avro serialized data into GenericRecord.
Unit and integration tests have been added
=> Avro GenericRecord implementation
