apache/pulsar-dotpulsar

- src/DotPulsar/Internal/ProducerStream.cs
To prevent default sends to stop working after two sends, set the cached metadata's sequence id
> Set the sequence id when sending using default metadata

- .gitignore
- src/DotPulsar/DotPulsar.csproj
- src/DotPulsar/FodyWeavers.xml
Following advise we always follow in libraries:. There's probably a couple more places where there's an explicit async/await where it can be avoided, as for example:
` public async Task Send(CommandPing command) => await Send(command.AsBaseCommand());`
can become
` public Task Send(CommandPing command) => Send(command.AsBaseCommand());`
- https://blog.stephencleary.com/2012/02/async-and-await.html
- https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f
- https://stackoverflow.com/questions/13489065/best-practice-to-call-configureawait-for-all-server-side-code
- https://msdn.microsoft.com/en-us/magazine/gg598924.aspx
> Improve asynchronous calls

- src/DotPulsar/Internal/ConnectionPool.cs
This adds proxy support which allows the client to work with (for example) managed Pulsar cluster providers such as Kafkaesque. Should be a nice boost in terms of making it more feasible for .NET shops to try out this technology.
I tested producing messages to:
- a remote Pulsar cluster running a Proxy (Kafkaesque free tier)
- a local standalone cluster
- a local standalone running a proxy
- a local standalone cluster running on Docker
I don't have a local or remote multi-broker setup with no proxy but I don't believe I modified the redirect logic so that use-case should continue to work as-is.
The bug I was having was that the ProxyToBrokerUrl field of a CommandConnect is expected in a very specific format and the proxy was returning a very unhelpful "Failed to authenticate" error which …
> Proxy support

- .asf.yaml
*Motivation*
Fix error `Invalid GitHub label '.NET' - must be lowercase alphanumerical and <= 35 characters!`
> Fix invalid Github label in .asf.yaml

- README.md
- src/DotPulsar/Internal/ConnectionPool.cs
This adds support for connection through a pulsar proxy. Tested against Kafkaeseque's SAAS offering.
This closes [Issue 36](https://github.com/apache/pulsar-dotpulsar/issues/36)
> Add Proxy support

- src/DotPulsar/MessageId.cs
- tests/DotPulsar.Tests/MessageIdTests.cs
In a confusingly ironic twist, using the new nullable language features in a public-facing area of this library has caused a bug where if a consumer checks a `MessageId` against `null` it will throw a NullReferenceException, which is pretty much the worst thing it could do in that scenario.  Since we target .net standard 2.0 and no particular language version as a library, we should be tolerant of such a check, even if it is not possible for that value to be null.
> Fix checking MessageId against null throwing NRE

- src/DotPulsar/Internal/ConsumerProcess.cs
- src/DotPulsar/Internal/ProducerProcess.cs
- src/DotPulsar/Internal/ReaderProcess.cs
Errors thrown in an async void method cannot be caught, resulting in application crashes in some cases.
> Eat errors in SetupChannel

- src/DotPulsar/Internal/DotPulsarEventSource.cs
The backing fields for the counters are `long`, so there was potential torn read on 32-bit platforms.
`Volatile.Read` ensures that the value is read in a atomic way, so no torn reads can occur.
> Fixed potential torn reads in EventCounters

- src/DotPulsar/Internal/Producer.cs
Currently if an exception happens in the Producer, the stack trace will look like this:
```
System.Net.Sockets.SocketException (11001): No such host is known.
at DotPulsar.Internal.Producer`1.ChoosePartitions(MessageMetadata metadata, CancellationToken cancellationToken)
at DotPulsar.Internal.Producer`1.Send(MessageMetadata metadata, TMessage message, CancellationToken cancellationToken)
[... My own code here...]
```
There is no functionality in the ChoosePartitions method that generates a SocketException, making the stack trace a bit useless.
This PR throws the exception stored in the `_throw` variable using ExceptionDispatchInfo thus retaining the original stack trace. In the case of the SocketException above, this becomes:
```
System.Net.Sockets.SocketException (11001): No such host is …
```
> Retain original stack trace when exception happens in Producer

- README.md
the current "hello world" will not show a consumed message the very first time it is run. On subsequent runs, it will work, but it isn't entirely clear from the code alone why it works on subsequent runs.
I don't entirely understand why the order matters here, but I believe it isn't showing the consumed message on the first run because the subscription is created after the producer sends a message. It seems that by default, a new subscription will not consume messages that are created before it.
An alternative solution would be to create the consumer with the "InitialPosition" option set to Earliest (".InitialPosition(SubscriptionInitialPosition.Earliest"), but I think it's preferable to minimize optional configuration in a hello world like this.
> modified the "hello world" to fix first run issue

- .editorconfig
- .idea/.idea.DotPulsar/.idea/codeStyles/Project.xml
- .idea/.idea.DotPulsar/.idea/codeStyles/codeStyleConfig.xml
- DotPulsar.sln.DotSettings
Updated .editorconfig to make ReSharper, Rider and VS2022 to use the same code style.
DotPulsar.sln.DotSettings updated so the Code cleanup profiles in ReSharper and Rider have the same behavior.
Deleted unnecessary folders according to dotpulsars .gitignore
> .editorconfig, DotPulsar.sln.DotSettings and removed folder

- .github/ISSUE_TEMPLATE/01_bug_report.yml
- .github/ISSUE_TEMPLATE/02_feature_request.yml
- .github/ISSUE_TEMPLATE/03_blank_issue.md
- CONTRIBUTING.md
Moved CONTRIBUTING.md to the root. So it is easier to see therefore, users don't have to go into the docs folder to find it.
Added 3 issue templates
Used the new issue forms to create:
01_bug_report.yml bug reporting
02_feature_request.yml new feature requests
Used plain old markdown
03_blank_issue.md stuff that doesn't fit the other categories
> Issue templates.

- .editorconfig
Removed 
end_of_line = crlf. Line endings are OS specific and should not be part of .editorcofig.
Added 
charset = utf-8. Defaulting all file encodings to UTF-8.
> cross platform compatibility

- tests/DotPulsar.Tests/Internal/Compression/ZstdCompressionTests.cs
Fixes zstd compression in the latest version is compiled to also work on linux
Fix test that was failing because it expected zstd compression not to work on linux
Test started failing after update of zstdnet package
> Zstd compression test fix

- CHANGELOG.md
- src/DotPulsar/Internal/AsyncQueueWithCursor.cs
Fixes Producer hang issue on reconnect
When disconnecting the semaphore preventing multiple NextItem() calls on AsyncQueueWithCursor was not properly released causing the next call on reconnect to wait forever.
This fixes a problem introduced in 2.8.0, when the producer send logic was rewritten.
Manual testing has been performed, but no integration tests are in place. I am not sure how we could implement an integration test for this.
> Fix Producer.Send hang on reconnect.

- src/DotPulsar/Internal/AsyncQueueWithCursor.cs
Fixes Issue causing wrong exception to be thrown when MoveNext() call was cancelled because of the queue being disposed
Calling MoveNext() incorrectly threw ObjectDisposedException when the AsyncQueueWithCursor was disposed while the caller was waiting. Should be TaskCancelledException.
Introduced by previous unreleased pull request.
Issue was already covered by existing tests
> Fix tests from previous pull request

- CHANGELOG.md
- src/DotPulsar/Internal/AsyncQueueWithCursor.cs
- src/DotPulsar/Internal/Producer.cs
Fixes Memory leak in producer
CancellationToken registration for Producer.Send operation was not correctly disposed
Introduced in 2.8.0 with internal rewrite of producer functionality
Manual testing with explicit garbage collection calls
> Fix memory leak in Producer

- CHANGELOG.md
- src/DotPulsar/Internal/AsyncLock.cs
- src/DotPulsar/Internal/CancelableCompletionSource.cs
- src/DotPulsar/Internal/SubProducer.cs
Fixes a memory leak in AsyncLock
Pending lock requests in AsyncLock had a registration that was never disposed.
Issue was introduced in initial commit
Manual testing with memory profiler
> Async lock leak

- src/DotPulsar/Internal/Producer.cs
Instead of passing in the Topic to GetNumberOfPartions use the class's Topic member.
`dotnet test` passed
Tested on Pulsar 2.11 instance with partitioned topics
> refactor(producer): Producer's GetNumberOfPartions

- tests/DotPulsar.Tests/IntegrationFixture.cs
Hopefully a fix for test Messages_GivenTopicWithMessages_ShouldConsumeAll that can get stuck and therefor fail
Upgraded the pulsar container image from version 2.10.3 to 2.11.0
Changed the message fluent docker looks for before it continues because the log message have changed between version 2.10.3 and 2.11.0
I have tested it on my computer.
> Hopefully a fix for a test that can get stuck

- CHANGELOG.md
- src/DotPulsar/Internal/Abstractions/IChannel.cs
- src/DotPulsar/Internal/Abstractions/IContainsProducerChannel.cs
- src/DotPulsar/Internal/Abstractions/IProducerChannel.cs
- src/DotPulsar/Internal/Abstractions/Process.cs
- src/DotPulsar/Internal/Channel.cs
- src/DotPulsar/Internal/ChannelManager.cs
- src/DotPulsar/Internal/Events/ProducerChannelConnected.cs
- src/DotPulsar/Internal/NotReadyChannel.cs
- src/DotPulsar/Internal/Producer.cs
- src/DotPulsar/Internal/ProducerChannel.cs
- src/DotPulsar/Internal/ProducerChannelFactory.cs
- src/DotPulsar/Internal/ProducerProcess.cs
- src/DotPulsar/Internal/SubProducer.cs
- src/DotPulsar/ProducerState.cs
- tests/DotPulsar.Tests/ProducerTests.cs
Fixes issues with Producer access modes
Fixes disconnect issues related to producer access modes.
Also changed behavior to to align with java client. When a producer with WaitForExclusive mode has been given 
exclusive access it cannot go back to WaitForExclusive, and will instead be fenced.
Issue introduced in unreleased code
Manual testing with TCP connection killing
> Producer access mode fixes

- README.md
The new [client feature matrix](https://pulsar.apache.org/client-feature-matrix/) page has been live, so this PR makes the required updates on the doc side.
Add a paragraph to notify both users and contributors about the new client feature matrix.
(Your PR needs to update docs and you will update later)
(Please explain why)
(Your PR contains doc changes)
(Docs have been already added)
> [Doc] Add links to client feature matrix in README.md

- CHANGELOG.md
- src/DotPulsar/Internal/Abstractions/Process.cs
- src/DotPulsar/Internal/ConsumerProcess.cs
- src/DotPulsar/Internal/ProducerProcess.cs
- src/DotPulsar/Internal/ReaderProcess.cs
Fixes Reader faulted issue
SetState unintentionally called twice resulting in reader channel not being faulted
> Reader faulted issue

- src/DotPulsar/Internal/Abstractions/Process.cs
- src/DotPulsar/Internal/ConsumerProcess.cs
- src/DotPulsar/Internal/ProducerProcess.cs
- src/DotPulsar/Internal/ReaderProcess.cs
Fixes Process disposal not terminating (in this specific format)
When disposing Process objects (ReaderProcess, ConsumerProcess, ProducerProcess) the call would never terminate.
Unreleased code
> Fix disposal of process not terminating

- CHANGELOG.md
- src/DotPulsar/Extensions/SendChannelExtensions.cs
- src/DotPulsar/Extensions/SendExtensions.cs
Fixes sequenceId not correctly set when using Send Extension methods and deduplication enabled.
Reset sequenceId before returning to pool for reuse
All other fields will not be sent when using the Send Extension methods and should therefore not have a value that needs to be reset.
> Feature/object pooling issue (#148)

- src/DotPulsar/Extensions/SendChannelExtensions.cs
- src/DotPulsar/Extensions/SendExtensions.cs
- src/DotPulsar/Internal/MessageMetadataObjectPool.cs
Ensures cleanup is consistent before returning objects to pool.
I have left the methods as public, which would allow users to reuse it in their own Send extension methods, but it does come with the caveat that those use cases may set properties that require cleanup. We could change the methods to be internal to prevent reuse.
> Centralize object pool for MessageMetadata

- CHANGELOG.md
- src/DotPulsar/Abstractions/IConsumer.cs
- src/DotPulsar/Abstractions/IGetLastMessageId.cs
- src/DotPulsar/Abstractions/IGetLastMessageIds.cs
- src/DotPulsar/Abstractions/IReader.cs
- src/DotPulsar/DotPulsar.csproj
- src/DotPulsar/Internal/ConnectionPool.cs
- src/DotPulsar/Internal/Consumer.cs
- src/DotPulsar/Internal/ConsumerChannel.cs
- src/DotPulsar/Internal/ConsumerChannelFactory.cs
- src/DotPulsar/Internal/Extensions/MessageIdDataExtensions.cs
- src/DotPulsar/Internal/Producer.cs
- src/DotPulsar/Internal/Reader.cs
- src/DotPulsar/Internal/SubConsumer.cs
- src/DotPulsar/Internal/SubProducer.cs
- src/DotPulsar/Internal/SubReader.cs
- src/DotPulsar/MessageId.cs
- src/DotPulsar/PulsarClient.cs
- tests/DotPulsar.Tests/ConsumerTests.cs
- tests/DotPulsar.Tests/DotPulsar.Tests.csproj
- tests/DotPulsar.Tests/MessageIdTests.cs
- tests/DotPulsar.Tests/ProducerTests.cs
- tests/DotPulsar.Tests/ReaderTests.cs
This PR adds partitioned topic support for the Consumer and Reader in DotPulsar.
Should you choose to accept this PR. I believe it will also pave the way for implementing multi-topic subscriptions https://github.com/apache/pulsar-dotpulsar/issues/5, later.
Major changes
The Consumer class is refactored, so its responsibility is to keep track of SubConsumers. Therefore, it is now the new SubConsumer class that has the actual obligation to consume on a topic. With this design change, the Consumer
now has the much-requested partitioned topic support. The Reader was also reworked to add partitioned topic support. The reader class keeps track of SubReaders, just like the Consumer class.
Implemented GetLastMessageIds in the Consumer and Reader. Therefore, in order to facilitate the use of the …
> Partitioned topic support

- src/DotPulsar/ConsumerState.cs
- src/DotPulsar/Internal/Consumer.cs
- src/DotPulsar/Internal/Reader.cs
- src/DotPulsar/ReaderState.cs
Consumer and Reader state system improved to handle partitioned topics
During the work on the state system the following bugs were found and fixed:
It seems that the Reader and Consumer failed to close their state properly during disposal.
SubReader and subConsumer may have mistakenly triggered the state system for the Reader and Consumer, respectively.
All tests are green
> Consumer and Reader state

- src/DotPulsar/Internal/Abstractions/IConnection.cs
- src/DotPulsar/Internal/Connection.cs
- src/DotPulsar/Internal/ConnectionPool.cs
- src/DotPulsar/Internal/PingPongHandler.cs
- tests/DotPulsar.Tests/Internal/PingPongHandlerTest.cs
Fixes #166 
The root cause of #166 is that the PingPongHandler doesn't work expectedly. 
The expected behavior for PingPongHandler is as follows:
- Send a ping every keepAliveIntervarl(default is 30s)
- Waiting for the Pong responses or any other command.
- Trigger the Watch task at the next keepAliveIntervarl. If there are no incoming commands in this period. Then the connection is dead, and we should dispose the connection.
But the current behavior is triggering the Watch every keepAliveIntervarl. If there are no incoming commands, then send the Ping. But there are no any actions to the connection.
I have also simplified the implementation of PingPongHandler. The previous implementation has the possible loss of fraction here: https://github.com/apache/pulsar-dotpulsar/blob/ab7b00315ea04d …
> Fix PingPongHandler doesn't kill the connection

- CHANGELOG.md
- src/DotPulsar/MessageId.cs
TryParse improvements
TryParse didn't guard for null or whitespace
Added missing feature in CHANGELOG.md
Improved code doc for TryParse
> TryParse missing CHANGELOG and dev docs

- CHANGELOG.md
- src/DotPulsar/Internal/ConsumerChannel.cs
When returning a MessageId, the topic should not be included if it is a MessageId.Earliest. Failure to remove the topic will cause issues when attempting to compare with another MessageId.Earliest.
All green
> GetLastMessageId Improvement

- CHANGELOG.md
- src/DotPulsar/Internal/Consumer.cs
- src/DotPulsar/Internal/Reader.cs
- src/DotPulsar/Internal/SubConsumer.cs
- src/DotPulsar/Internal/SubReader.cs
- tests/DotPulsar.Tests/ConsumerTests.cs
- tests/DotPulsar.Tests/ReaderTests.cs
The Consumer and Reader didn't throw FaultedException in two scenarios where it should.
Consumer
1:
After the initial setup of the DotPulsar client where it can't connect to the cluster. Creating a consumer and using Receive didn't produce a ConsumerFaultedException as it should.
2:
After the initial setup of the DotPulsar client where it can't connect to the cluster and is in a faulted state. Creating a consumer and using Receive didn't produce a ConsumerFaultedException as it should.
Reader
1:
After the initial setup of the DotPulsar client where it can't connect to the cluster. Creating a reader and using Receive didn't produce a ReaderFaultedException as it should.
2:
After the initial setup of the DotPulsar client where it can't connect to the cluster and is in a faulted state. …
> Consumer and Reader do not throw FaultedException as excepted.

- CHANGELOG.md
- src/DotPulsar/Internal/SubReader.cs
- tests/DotPulsar.Tests/ConsumerTests.cs
- tests/DotPulsar.Tests/ReaderTests.cs
Consumers and readers were attaching the topic name even when there were no messages available. This issue has been resolved in https://github.com/apache/pulsar-dotpulsar/pull/175 in the ConsumerChannel. However, the SubReader code was still adding the topic unnecessarily. I have now removed this code and added tests to ensure that both the reader and consumer are functioning properly.
All test green
> SubReader still attached topic name on a topic with no messages.

- .github/workflows/ci-unit.yaml
Fixes GHA: Artifacts #182
Our CI pipeline works with artifacts, but I don't think we really use them for anything.
I opened an issue #182 trying to figure out why it was added in 2020 and what it does.
Now it has nearly been a week without any response.
Testing this change is challenging since GitHub doesn't offer a GHA testing environment. Therefor, I have not been able to test if it breaks anything.
However, it is worth noting that, based on the available information, it appears that we are not actively utilizing these artifacts.
> Remove the unused artifacts from the ci-unit.

- .github/workflows/ci-unit.yaml
When reviewing a pull request, duplicated errors pollute the code view unnecessarily.
Example
When reviewing code. We just want a clean view to do it.
> Stop duplicate code comments for code review.

- .github/workflows/publish-to-nuget.yml
- docs/release-process.md
- src/DotPulsar/DotPulsar.csproj
Fixes
**Issue Link**: [GitHub Issue #117](https://github.com/apache/pulsar-dotpulsar/issues/117)
**Issue Link**: [GitHub Issue #159](https://github.com/apache/pulsar-dotpulsar/issues/159)
**Issue Link**: [GitHub Issue #28](https://github.com/apache/pulsar-dotpulsar/issues/28)
This GitHub Actions (GHA) workflow automates the release process for our software to NuGet. The NuGet package is versioned based on git tags.
The process among other things involve using GitHub releases:
1. Create or select an existing tag.
2. Enter a release title.
3. Generate release notes.
4. Push the release to GitHub.
For detailed explanation, please read release-process.md in this commit.
Testing this workflow is challenging since GitHub doesn't offer a straightforward testing environment. I initially tested it …
> Release process and GitHub Action to release a NuGet packages, based on tags.

- .github/workflows/publish-to-nuget.yml
- docs/release-process.md
- src/DotPulsar/DotPulsar.csproj
The version tag has been removed from the DotPulsar.csproj file, as the continuous delivery (CD) pipeline now uses the git tag as version information. Additionally, the ContinuousIntegrationBuild in the file has been removed and moved to publish-to-nuget.yml, so it can be handled by a command line switch to dotnet. We have also updated the release-process.md file to reflect the change that version information is no longer needed in the DotPulsar.csproj file.
Testing this workflow is challenging since GitHub doesn't offer a straightforward testing environment. I initially tested it on my personal project, [nugettestrepo_delete_me_soon](https://github.com/entvex/nugettestrepo_delete_me_soon), and confirmed its functionality. Later, I adapted the GHA configuration to match the DotPulsar …
> Streamlined the release process for DotPulsar.

- tests/DotPulsar.Tests/DotPulsar.Tests.csproj
- tests/DotPulsar.Tests/IntegrationFixture.cs
This commit adds Toxiproxy to our system to help us simulate common issues in distributed systems such as fault tolerance and error recovery. This will help us identify and fix issues before they become critical.
> Add Toxiproxy to simulate errors in distributed systems

- CHANGELOG.md
- src/DotPulsar/RoundRobinPartitionRouter.cs
- src/DotPulsar/SinglePartitionRouter.cs
- tests/DotPulsar.Tests/DotPulsar.Tests.csproj
- tests/DotPulsar.Tests/Internal/RoundRobinPartitionRouterTests.cs
- tests/DotPulsar.Tests/Internal/SinglePartitionRouterTests.cs
Fixes #213
Adjustments have been made to the implementation of SinglePartitionRouter and RoundRobinPartitionRouter so the that the ChoosePartition method return non-negative integers.
Added unit tests for the SinglePartitionRouter and RoundRobinPartitionRouter classes. These tests check that chosen partitions return non-negative integers.
> Add partition router tests and update xunit packages

- .github/workflows/codeql.yml
The CodeQL analysis workflow has been updated to include more detailed specifications for the analysis and build process. This includes adding information for runner and hardware resources considerations, permissions required for private CodeQL packs and private repositories, and increased detail on language analysis support. The build mode is now customizable, which allows for more control over how the codebase is analyzed. The upgrade of the analysis version to v3 has resulted in overall improvements to the security analysis of the codebase.
> Updated CodeQL workflow now that it supports DotNet 8

- CHANGELOG.md
- src/DotPulsar/Internal/Producer.cs
Fixes #{224}
A special case where a consumer closes before being connected, cause a non descriptive exception to be thrown to the user.
Conditions manually created by inserting delays in source code.
> Handle disconnect -> close properly in ChoosePartions

- .github/workflows/ci-unit.yaml
- .github/workflows/publish-to-nuget.yml
Updated the `dotnet-version` to '9.0.x' in both publish-to-nuget and ci-unit workflow YAML files. This ensures compatibility with the latest .NET features and improvements, enhancing the build and test processes.
> Update .NET version to 9.0.x in workflows

- src/DotPulsar/Abstractions/IReaderBuilder.cs
- src/DotPulsar/Internal/Reader.cs
- src/DotPulsar/Internal/ReaderBuilder.cs
- src/DotPulsar/ReaderOptions.cs
Currently the reader creation uses a hardcoded setup of: 
` var subscription = $"Reader-{correlationId:N}";`
Which creates the non durable subscription in Pulsar with that name for the reader instance.
However Pulsar offers a authz part where the subscription name matters due to the prefix of the subscription name being used to give access to the topic.
With that authz setting enabled and a non durable subscription that doesn't contain a prefix Wil result Pulsar giving this exception:
`AuthorizationException: org.apache.pulsar.broker.PulsarServerException: Failed to create consumer - The subscription name needs to be prefixed by the authentication role, like 674cea0f-ea2a-4358-804e-66d5fc732169-xxxx `
So this change enables configurating of a prefix for the subscription that's created …
> Add possibility of setting a prefix for the subscription for readers.

- samples/Consuming/Program.cs
- samples/Consuming/Properties/launchSettings.json
- samples/Producing/Program.cs
- samples/Producing/Properties/launchSettings.json
- samples/Producing/SendChannelWorker.cs
- samples/Producing/SendWorker.cs
Fixes Running different workers in new examples require code change and rebuild
Make the Worker configurable in the Producing and Consuming samples and add launchSettings for each worker
> Add launch configurations for different workers i examples
